# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_login', '0001_initial'),
        ('djangoDemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='user_created',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to='new_login.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_other',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_other', to='new_login.User'),
        ),
    ]
